- name: install and run nginx
  hosts: web
  become: yes   # It will get root access
  tasks:
  - name: install nginx package
    ansible.builtin.package:        # This is module, we can use dnf also in place of package, we can use any module because ansible is rich in modules
      name: nginx
      state: present         # Present = installing
  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: started        # Started = Running the instance