- name: install and run nginx
  hosts: web
  become: yes #it will get root access
  tasks:
  - name: install nginx package
    ansible.builtin.package:        # this is module
      name: nginx
      state: present         # present is nothing but installing
  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: started