# playbook "-"is a list of Plays
- name: PLAY-1
  hosts: localhost  # not only external it can also connect to the local hosts also
  tasks:
  - name: PLAY-1 and TASK-1
    ansible.builtin.debug:   # it will print what ever you give thats y this module
      msg: "Hello from PLAY-1 and TASK-1"

- name: PLAY-2
  hosts: localhost
  tasks:
  - name: PLAY-2 and TASK-2
    ansible.builtin.debug:
      msg: "Hello from PLAY-2 and TASK-2"