# PLAY level variables
- name: variables from PLAY level
  hosts: localhost
  vars:
    Course: "DevOps"
    Trainer: "Sivakumar"
    Duration: "110HRS"
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "Hi, I am learning {{Course}}, Trainer is {{Trainer}}, Duration is {{Duration}}"


# Variables concept:- Dry concept, dont repeat yourself, we can keep variables aside from the code, so that code will not get disturb when we are doing changes, variables holds a value you can use it anywhere in the task level if you give variables in play-level. So to call a variable in ansible we use two flower brases {{ }}, we can give variables in play level and can be used anywhere in the task level