- name: variables from PLAY level
  hosts: localhost
  vars: # Play level variables
    Course: "DevOps"  
    Trainer: "Sivakumar"
    Duration: "110HRS"
  tasks:
  - name: check variables
    vars: # Task level variables
      Course: "DevOps with AWS"
    ansible.builtin.debug:
      msg: "Hi, I am learning {{Course}}, Trainer is {{Trainer}}, Duration is {{Duration}}"


# So now tell me which one will pick? variables from play level(or)from task level?,task level variables will be picked because task level variables can over write play level variables that is the concept of inheritence