# TASK level variables
- name: variables from PLAY level
  hosts: localhost
  vars:
    Course: "DevOps"
    Trainer: "Sivakumar"
    Duration: "110HRS"
  tasks:
  - name: check variables
    vars: #task level
      Course: "DevOps with AWS"
    ansible.builtin.debug:
      msg: "Hi, I am learning {{Course}}, Trainer is {{Trainer}}, Duration is {{Duration}}"


# So now tell me which one will pick? variables from play level(or)from task level?,task level variables can over write play level that is the concept of inheritence
# Task level variables can overwrite play level variables, like it as inheritence