- name: variables from PLAY level
  hosts: localhost
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "Hello {{PERSON}}, Good {{WISHES}}"



# how to give args from the command line ?
# ansible-playbook -i inventory.ini -e ansible _user=centos -e ansible_password=DevOps321 -e "PERSON=Saikiran" -e "WISHES=Morning" <file-name>