- name: ping playbook
  hosts: localhost
  tasks:
  - name: ping the server
    ansible.builtin.ping:

  - name: print message
    ansible.builtin.debug:
      msg: "Hello DevOps"
    tags:
    - devops
  
  - name: print message
    ansible.builtin.debug:
      msg: "Hello AWS"
    tags:
    - aws


    # In the server --> if you want only to run a particular tags then we can use the command like
    # ansible-playbook -t devops 16-tags.yaml
    # ansible-playbook -t aws 16-tags.yaml