- name: ping playbook
  hosts: localhost
  tasks:
  - name: ping the server
    ansible.builtin.ping:

  - name: print message
    ansible.builtin.debug:
      msg: "Hello DevOps"
    tags:
    - devops
  
  - name: print message
    ansible.builtin.debug:
      msg: "Hello AWS"
    tags:
    - aws


    # In the server --> If you want a particular task then you can use the tags
    # ansible-playbook -t devops 16-tags.yaml
    # ansible-playbook -t aws 16-tags.yaml

    # When we can use tags?
    # For example take a catalogue component, if there is any new version of catalogue, what will you do basically ? we do new deployment/new release right ?
    # 1.Stop the server
    # 2.Remove old code
    # 3.Download the latest code
    # 4.Restart the server
    # So in the common role i give deployment.yaml mention all the above 4 tasks including tags in it and then use the tags in the server for deployment
    # Command will be ansible-playbook -e component=catalogue -t deployment main.yaml